export const UPDATEARTICLES = 'UPDATEARTICLES'
export const UPDATECURRENTSELECTEDARTICLE = 'UPDATECURRENTSELECTEDARTICLE'

// classify
export const UPDATECLASSIFIES = 'UPDATECLASSIFIES'
export const UPDATECURRENTSELECTCLASS = 'UPDATECURRENTSELECTCLASS'
export const UPDATECURRENTSELECTCLASSARTICLES = 'UPDATECURRENTSELECTCLASSARTICLES'