export const UPDATEARTICLES = 'UPDATEARTICLES'
export const UPDATECURRENTSELECTEDARTICLE = 'UPDATECURRENTSELECTEDARTICLE'
export const UPDATEARTICELSBYCLASSNAME = 'UPDATEARTICELSBYCLASSNAME'

// admin
export const UPDATECLASSIFIES = 'UPDATECLASSIFIES'
export const UPDATECURRENTSELECTCLASS = 'UPDATECURRENTSELECTCLASS'
export const UPDATECURRENTSELECTCLASSARTICLES = 'UPDATECURRENTSELECTCLASSARTICLES'
export const NEWARTICLE = 'NEWARTICLE'